apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible
  annotations:
    github.com/project-slug: badal1443/ansible
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
