apiVersion: backstage/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    This github repo shows how to use ansible to create and configure azure resources.
  links:
    - title: Website
      url: http://github.com/badal1443/Ansible
    - title: Documentation
      url: http://github.com/badal1443/Ansible/docs
    - title: Storybook
      url: https://backstage.io/storybook
  annotations:
    github.com/project-slug: badal1443/ansible
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: Badal
  lifecycle: experimental
