- name: Python installation on linux
  hosts: twinpeaks
  become: true
  tasks:
    - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Update repositories cache and install "python 3.6" package
      ansible.builtin.apt:
        name: python3.6
        update_cache: yes
    - name: Install Python 3.6 but do not select it
      community.general.alternatives:
        name: python
        path: /usr/bin/python3.6
        link: /usr/bin/python
        state: present
