site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/badal1443/Ansible
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'
