---
- name: Provision Ubuntu Machine in Azure
  hosts: localhost
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: backstageRG
        location: eastus

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: backstageRG
        name: myVnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: backstageRG
        name: mySubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: myVnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: backstageRG
        allocation_method: Static
        name: myPublicIP

    - name: Create network security group
      azure_rm_securitygroup:
        resource_group: backstageRG
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: backstageRG
        name: myNIC
        virtual_network: myVnet
        subnet: mySubnet
        security_group: myNetworkSecurityGroup
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: publicip001
            primary: true
    - name: Create an availability set for managed disk vm
      azure_rm_availabilityset:
        name: avs-managed-disk
        resource_group: backstageRG
        platform_update_domain_count: 5
        platform_fault_domain_count: 2
        sku: Aligned

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: backstageRG
        name: myVM
        vm_size: Standard_D4
        availability_set: avs-managed-disk
        managed_disk_type: Standard_LRS
        admin_username: irobot
        admin_password: irobot123!
        ssh_password_enabled: true
        network_interfaces: myNIC
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: Canonical
          sku: 20_04-lts-gen2
          version: latest
